version: "3.8"

services:


  django-back:
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./PartyTimeBotBack/app
      dockerfile: Dockerfile
    volumes:
      - ./PartyTimeBotBack/app:/usr/src/app
      - ./PartyTimeBotBack/app/db.sqlite3:/usr/src/app/db.sqlite3
      - ./PartyTimeBotBack/app/static:/usr/src/app/static

    ports:
      - "8001:8001"
    restart: always
    networks:
      - network_rs

networks:
  network_rs:
    driver: bridge

volumes:
  static_volume: